dlokas=['Rangkasbitung, Jawa Barat, Indonesia','Pandeglang, Jawa Barat, Indonesia','Serang',
'Citerep, Ciruas','Tegalsari, Tigaraksa','Ciputat','Cilegon, Banten',
'Pabuaran, Tangerang','Soreang, Bandung','Bandung','Ngamprah','Banjar','Cikarang, Cilamaya','Bekasi',
'Cibinong, Bogor','Bogor, Indonesia','Ciamis, Jawa Barat, Indonesia','Kota Cimahi','Cirebon','Cianjur, Cianjur, Jawa Barat','Depok','Indramayu',
'Sukabumi','Karawang','Tasikmalaya','Kuningan, Kuningan','Singaparna, Jawa Barat, Indonesia','Sumedang','Parigi',
'Palabuhanratu, Jawa Barat, Indonesia','Purwakarta','Subang Jaya','Garut',
'Banjarnegara','Kudus',
'Purwokerto','Klaten',
'Batang','Mungkid',
'blora','pati',
'Boyolali','Kajen',
'brebes','Pemalang',
'Cilacap','Purbalingga',
'Demak','Purworejo',
'Kebumen','Rembang',
'Karanganyar','Ungaran',
'Jepara',	
'Purwodadi','Sukoharjo',
'Slawi','kendal',
'Temanggung','Surakarta',
'Magelang','Semarang',
'Pekalongan',  'wonogiri',
'Bangkalan','Nganjuk',
'Banyuwangi','pamekasan',
'Kanigoro',	
'Bojonegoro','Ngawi',
'Bondowoso','Bangil',
'Gresik','Ponorogo',
'jember','Kraksaan',
'Jombang','Sampang',
'Ngasem','Sidoarjo',
'Lamongan','Situbondo',
'Lumajang','Sumenep',
'Caruban','Trenggalek',
'Magetan','Tuban',
'Tulungagung',
'Mojosari','Batu',
'Mojokert',
'Kediri','Pasuruan','Probolinggo',
'Malang','surabaya',

'Kota Binjai',
'Stabat, Sumatera Utara',
'Medan, Indonesia',
'Panyabungan, Sumatera Utara',
'Kota Padang Sidempuan',
'Kota Pematangsiantar',
'Kota Sibolga',
'Tanjungbalai, Riau',
'Kota Tebing Tinggi',	

'Tenggarong, Kalimantan Timur',
'Balikpapan',
'Samarinda',
                            
'Tebo, East Java',
'Bangko, Jambi',
'Kota Jambi',
'Sungaipenuh, Jambi',	

'Bengkalis, Riau',
'Dumai',
'Pekanbaru',

'Lubukbasung, Sumatera Barat',
'Kota Bukittinggi',
'Padang',
'Kota Pariaman'	,
'Solok',

'Banda Aceh',
'Kota Langsa',
'Kota Lhokseumawe',
'Kota Sabang',
'Penanggalan, North Sumatra',

'Ampenan Selatan',		
'Taliwang, Nusa Tenggara Barat',
'Cakranegara Selatan, Cakranegara',	
'Sumbawa, Nusa Tenggara Barat',
'Mataram',
'Tanjung',
'Potu, Dompu',

'Bengkulu, Bengkulu',
'Kepahiang, Bengkulu',
'Argamakmur, Bengkulu',

'Badung, Bali',
'Kuta, Badung',	
'Negara, Bali',
'Bangli, Bali',	
'Amlapura, Bali',	
'Semarapura Kelod',
'Gianyar',
'Kabupaten Tabanan',
'Denpasar, Bali',
]
